SERVICE_ACCT_USERNAME: irods
SERVICE_ACCT_GROUP: irods
IRODS_ZONE: b3devZone
IRODS_PORT: 1247
RANGE_BEGIN: 20000
RANGE_END: 20199
VAULT_DIRECTORY: /home/irods/Vault
ZONE_KEY: TEMPORARY_zone_key
NEGOTIATION_KEY: TEMPORARY_32byte_negotiation_key
CONTROL_PLANE_PORT: 1248
CONTROL_PLANE_KEY: TEMPORARY__32byte_ctrl_plane_key
SCHEMA_VALIDATION_BASE_URI: https://schemas.irods.org/configuration
ADMINISTRATOR_USERNAME: rods
ADMINISTRATOR_PASSWORD: rods
HOSTNAME_OR_IP: irods-db
DATABASE_PORT: 5432
DATABASE_NAME: ICAT
DATABASE_USER: irods
DATABASE_PASSWORD: irods
